# Generated by Django 4.2.20 on 2025-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
